trigger:
- master  # Adjust to your branch name

pool: Default
  

variables:
  MAVEN_OPTS: "-Xmx1024m"
  SONAR_PROJECT_KEY: 'azdevopslt_azure-devops'
  SONAR_ORGANIZATION: 'azdevopslt'
  SONAR_TOKEN: '25506995eaf522f172de92ee925a7b90a1baa299' # Add this as a secret variable in Azure DevOps
  SONAR_PROJECT: 'azdevopslt'


steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-B'
    goals: 'clean package'
  displayName: 'Maven Compile'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SONAR_CLOUD_1' # Replace with your SonarCloud service connection name
    organization: '$(SONAR_ORGANIZATION)'  # Replace with your SonarCloud organization name
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(SONAR_PROJECT_KEY)'       # Replace with your SonarCloud project key
    cliProjectName: '$(PROJECT)'     # Replace with your SonarCloud project name
    cliProjectVersion: '1.0'
    extraProperties: |
      sonar.java.binaries=target/classes
      sonar.sources=src/main/java
      sonar.tests=src/test/java
      sonar.junit.reportPaths=target/surefire-reports
      sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
  displayName: 'Prepare analysis on SonarCloud'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'verify sonar:sonar'
    options: '-Dsonar.login=$(SONAR_TOKEN)'
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate Result'
