---
name: CI with Maven
on:
  push:
    branches:
      - main
jobs:
  buildwith17:
    name: "maven"
    runs-on: ubuntu-24.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.USERNAME }}
        run: |
          example-command "$SUPER_SECRET"
      

