---
name: CI with Maven
on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: dummyrepos/ReusableWorkflows/.github/workflows/maven/basic.yaml@main
    with:
      goal: package
      java_version: '17'
      

